### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by ZYB0726** [xiaozai/DeT#14]
Hi,
Is there an evaluation code for this dataset? Or how did you evaluate it?

**Comment by xiaozai** [comment]
Hi , we used the VOT toolkit for evaluation. For frame-based metrics, we merged all sequences into one sequence.

**Comment by ZYB0726** [comment]
I see. Thank you for your reply.

---Original---
From: "Yan ***@***.***&gt;
Date: Mon, Dec 5, 2022 12:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xiaozai/DeT] Evaluation code (Issue #14)




 
Hi , we used the VOT toolkit for evaluation. For frame-based metrics, we merged all sequences into one sequence.
