### ISSUE TITLE
About depth image bit?

### ISSUE THREAD

**Issue by laisimiao** [xiaozai/DeT#2]
In "DepthTrack: Unveiling the Power of RGBD Tracking" it said
>  RGB images were stored as 24-bit JPEG with low compression rate and the depth frames as 16-bit PNG. 

I use following code to read depth png:
```
from PIL import Image
import numpy as np
a = np.array(Image.open('....../adapter02_indoor/depth/00000001.png'))
```
And I find it's dtype is `int32`, how to understand?

**Comment by xiaozai** [comment]
Hi,
 When we recorded depth images, we did use the 16-bit to save it.
When we read the depth image, we usually use the cv2.imread(depth, -1)
which uses the 16-bit as well.
 We don't recommend to use numpy.

BR,
Song Yan

laisimiao ***@***.***> 于 2022年1月8日周六 10:50写道：

**Comment by laisimiao** [comment]
Ok, so when you save generated depth image, do you also use `cv2.imwrite()`?

**Comment by xiaozai** [comment]
Hi,
Yes, we used cv2. We assume that 1000 represents 1 meter, and the target is
at most 10 meters.

 For the generated images, we can not guarantee the distance range, but the
generated distance is from 0 to 1, so we map it to 10 meters for most
images.

As we said, we recommend that you generate the depth images by yourself,
then you van decide the depth range and 16-bit or 32-bit and remove bad
images. Even you can use other sota monocular depth estimation methods for
a better result.

BR,
Song Yan

laisimiao ***@***.***> 于 2022年1月8日周六 10:56写道：

**Comment by laisimiao** [comment]
So in DepthTrack(or CDTB), the max value is 65535 and it stands for 10m=10000mm, right?  And we can calculate its true distance using pixel_value / 65535 * 10000 (mm)?

**Comment by xiaozai** [comment]
For real depth images, the truth distance is x / 1000 meters, but most
targets locate at 0 - 10 meters. Usually i used 5 meters to normalize
indoor images, for example, img = max(img, 5000) , which will generate
better visualization.  And i used 9 meters to normalize outdoor images.

Another option is that to get the target distance in the bbox of the first
image, then double it as the maximum distance to normalize the depth images.

laisimiao ***@***.***> 于 2022年1月8日周六 11:07写道：

**Comment by xiaozai** [comment]
When you used cv2.imread(img, -1), you don't need to multiply 65535. Just
pixel values / 1000 . But i think mm is better than meters.
I set the range of (0, 10000) mm instead of (0, 10) meters.

laisimiao ***@***.***> 于 2022年1月8日周六 11:07写道：

**Comment by xiaozai** [comment]
In our code, we use 10 meters as the most distance to normalize all images and then generated the colormaps as inputs.

We had another idea that uses different kernels to process depth images. For example, a convolutional layer is 10xHxW, the first can process 0-1000, the second can process 1000-2000, and so on. It can distinguish the background and target. We tired, but we didn't get very good results.

**Comment by laisimiao** [comment]
wait, I am new to depth image, let me digest it and try write code to valid it. I'm curious the process to save depth image, like you get the depth video from intel D415 camera and split it into frame by frame, and so far its pixel value is absolute distance (mm) and you clip values by setting a max depth.  Such as pixel value is between (0,5000) in indoor scenes and (0,5000) is normalized into (0,65535) and use `cv2.imwrite` to save it into png image. Do I misunderstand some parts?

**Comment by xiaozai** [comment]
No, when you get frames from intel realsense, you just use the cv2.imwrite
to save the depth images into 16-bit png, and do not use the clip.
Intel realsense provides the instructions of how to capture and save images.

When you read from images for tracking, you use cv2.imread(img, -1) to get
the depth images in mm.

Then if you want to process the depth iamges for further usages, for
example, colormaps, you can clip the depth values.
You can also use the raw depth iamges if you want.

laisimiao ***@***.***> 于 2022年1月8日周六 11:37写道：

**Comment by xiaozai** [comment]
Actually, in other works, people do not process the depth images. They just use the depth histogram in the bounding box region, no matter in mm or meters. 
In our works, we want to get the colormaps, so we clip the depth images into 0-10meters for a better visualization.
If you don't need the colormap, you don't need to clip the depth images.

**Comment by laisimiao** [comment]
Oh, I see. So clipping is just used for visualization? You help me a lot in this matter.

**Comment by xiaozai** [comment]
Here is the sample code from Intel Realsense, maybe it will help you to understand the process:
```
import pyrealsense2 as rs
import numpy as np
import cv2

pipeline = rs.pipeline() # Create a pipeline

config = rs.config()    # Create a config and configure the pipeline to stream
config.enable_stream(rs.stream.depth, 640, 320, rs.format.z16, 30) # 30 fps, 640*320 resolution
config.enable_stream(rs.stream.color, 640, 320, rs.format.bgr8, 30) 

profile = pipeline.start(config) # Start streaming

depth_sensor = profile.get_device().first_depth_sensor() # Getting the depth sensor's depth scale (see rs-align example for explanation)
depth_scale = depth_sensor.get_depth_scale()
print("Depth Scale is: " , depth_scale)

clipping_distance_in_meters = 1 #1 meter
clipping_distance = clipping_distance_in_meters / depth_scale #  clipping_distance_in_meters meters away

align_to = rs.stream.color
align = rs.align(align_to) # rs.align allows us to perform alignment of depth frames to others frames

index = 0
try:
    while True:
        frames = pipeline.wait_for_frames()
        aligned_frames = align.process(frames) # Align the depth frame to color frame
        aligned_depth_frame = aligned_frames.get_depth_frame()  # Get aligned frames
        color_frame = aligned_frames.get_color_frame()
        
        if not aligned_depth_frame or not color_frame:
            continue
        
        depth_image = np.asanyarray(aligned_depth_frame.get_data())
        color_image = np.asanyarray(color_frame.get_data())

        depth_colormap = cv2.applyColorMap(cv2.convertScaleAbs(depth_image, alpha=0.03), cv2.COLORMAP_JET)
        images = np.hstack((color_image, depth_colormap))
        
        cv2.namedWindow('Aligned Images and Depth', cv2.WINDOW_AUTOSIZE)
        cv2.imshow('Align Images and Depth', images)
        
        key = cv2.waitKey(100)
        if key & 0xFF == ord('q') or key == 27:
            cv2.destroyAllWindows()
            break
            
        cv2.imwrite('%08d_rgb.png'%index, color_image) # Save images and depth
        cv2.imwrite('%08d_depth.png'%index, depth_image)
        index += 1
finally:
    pipeline.stop()
```

**Comment by laisimiao** [comment]
Hi, @xiaozai 
Thank you for your detailed help! 
But it seems that the range of camera is 65535 / 1000 ~= 65m (those distance exceeds 65535 will be set zero automatically when saved as 16bit), which is dependent on the saved bit but camera's phisical max range is independent and should have no relationship with saved bit?

**Comment by xiaozai** [comment]
Yes, exactly. Usually the target distance range will be 0-10 meters, and
the sensor can not capture depth cues if it is too far away. That's why
there are pixels with missing values.

laisimiao ***@***.***> 于 2022年1月8日周六 14:59写道：
