### ISSUE TITLE
How to generate the F-score, Precision and Recall

### ISSUE THREAD

**Issue by pilot00** [xiaozai/DeT#7]
Hello,

It's really great that you guys have disclosed such an excellent work.

I would like to know how to obtain the F-score, precision and recall values when I get the raw results with '.txt' suffix?

Thanks a lot!

**Comment by xiaozai** [comment]
Hi， 
 You can use vot toolkit to generate Pr, Re, F-score. 
 https://github.com/votchallenge/toolkit

 In our paper, we use the sequence-based evaluation and frame-based evaluation. Sequence-based evaluation is just the vot evaluation, and frame-based evaluation is used to illustrate the effects of video lengths. Frame-based evaluation means merging all videos into one video. In the VOT2021 challenge, we only use the vot evaluation. So you can just use the sequence-based (vot) evaluation. 
 
Remember to convert all [x, y, -1, -1 ] or [x, y, 0, 0] into [nan. nan, nan. nan], which are target-disappearance frames.

**Comment by pilot00** [comment]
Apart from the target-disappearance frames labels being converted to [nan. nan, nan. nan], what do I need to change for the vot toolkit to fit your test set?

**Comment by xiaozai** [comment]
Same as how to test cdtb, just change cdtb sequences to depthtrack test sequences.

**Comment by pilot00** [comment]
OK, I got it. Thanks a lot!
